// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrsqv2cBIMNOaMI5-8748GJJDXaXjz0h4',
    appId: '1:699147444489:web:a93177f5aabb9ddfeb73d8',
    messagingSenderId: '699147444489',
    projectId: 'autism-app-80266',
    authDomain: 'autism-app-80266.firebaseapp.com',
    storageBucket: 'autism-app-80266.appspot.com',
    measurementId: 'G-RBPXCWB4PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq9deAwQwstP28ipvYCKSgpjxFtH4Ky04',
    appId: '1:699147444489:android:5e8721db923ff51aeb73d8',
    messagingSenderId: '699147444489',
    projectId: 'autism-app-80266',
    storageBucket: 'autism-app-80266.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkS3K376vPiVEA2Pm0CbZA3PF4Ec7gTuo',
    appId: '1:699147444489:ios:2c1b124fcd772f4beb73d8',
    messagingSenderId: '699147444489',
    projectId: 'autism-app-80266',
    storageBucket: 'autism-app-80266.appspot.com',
    iosBundleId: 'com.example.autismApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkS3K376vPiVEA2Pm0CbZA3PF4Ec7gTuo',
    appId: '1:699147444489:ios:2c1b124fcd772f4beb73d8',
    messagingSenderId: '699147444489',
    projectId: 'autism-app-80266',
    storageBucket: 'autism-app-80266.appspot.com',
    iosBundleId: 'com.example.autismApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrsqv2cBIMNOaMI5-8748GJJDXaXjz0h4',
    appId: '1:699147444489:web:7ab99784230791f7eb73d8',
    messagingSenderId: '699147444489',
    projectId: 'autism-app-80266',
    authDomain: 'autism-app-80266.firebaseapp.com',
    storageBucket: 'autism-app-80266.appspot.com',
    measurementId: 'G-VJM3WXC8C9',
  );
}
